apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: pareshpawar/simple-http-server
        resources:
          limits:
            cpu: "250m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-server
  labels:
    run: simple-http-server
spec:
  selector:
    app: simple-http-server
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001
  type: NodePort
